package russell_cmis440_lab3;


/**
* Program Name: CMIS440 Lab 3 JavaDB Address Book Program
* @author Brandon R Russell
* @Course CMIS440
* Date: Dec 15,2010
* IDE: NetBeans 6.9.1
* OS: Windows 7
* Java: JDK 1.6.0_22
* Files:
*
* Program Requirements:
*
*
* Things you what me to know before I grade your work: I used the NetBeans
* Graphic designer to create the GUI portion of this program.
*/



import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
        
public class AddressBookDisplay extends javax.swing.JFrame {

   private Person currentEntry;
   private PersonQueries personQueries;
   private List< Person > results;
   private int numberOfEntries = 0;
   private int currentEntryIndex;

    /** Creates new form AddressBookDisplay */
    public AddressBookDisplay() {
        //super( "Address Book" );
        // establish database connection and set up PreparedStatements
        personQueries = new PersonQueries();
        initComponents();
        loadDatabase();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browsePanel = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        txtCurrentRecord = new javax.swing.JTextField();
        lblOf = new javax.swing.JLabel();
        txtTotalRecordCount = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        myJTable = new javax.swing.JTable();
        lblNoData = new javax.swing.JLabel();
        newUpdateDeletePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAddressID = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhoneNum = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        btnNewEntry = new javax.swing.JButton();
        btnUpdateEntry = new javax.swing.JButton();
        btnDeleteEntry = new javax.swing.JButton();
        findPanel = new javax.swing.JPanel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        errorPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        debugTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CMIS440 Lab 3 JavaDB Address Book Program");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.Desktop.background"));

        browsePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Browse"));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        txtCurrentRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentRecordActionPerformed(evt);
            }
        });

        lblOf.setText("of");

        txtTotalRecordCount.setEnabled(false);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        myJTable.setModel(personQueries);
        myJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        myJTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                myJTablePropertyChange(evt);
            }
        });
        ListSelectionModel rowSM = myJTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                myJTableValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(myJTable);

        lblNoData.setForeground(javax.swing.UIManager.getDefaults().getColor("nb.errorForeground"));
        lblNoData.setText("*No Data Present");

        javax.swing.GroupLayout browsePanelLayout = new javax.swing.GroupLayout(browsePanel);
        browsePanel.setLayout(browsePanelLayout);
        browsePanelLayout.setHorizontalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browsePanelLayout.createSequentialGroup()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(browsePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                    .addGroup(browsePanelLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCurrentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalRecordCount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browsePanelLayout.createSequentialGroup()
                        .addContainerGap(602, Short.MAX_VALUE)
                        .addComponent(lblNoData)))
                .addContainerGap())
        );

        browsePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCurrentRecord, txtTotalRecordCount});

        browsePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNext, btnPrevious});

        browsePanelLayout.setVerticalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browsePanelLayout.createSequentialGroup()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnPrevious)
                    .addComponent(txtCurrentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOf)
                    .addComponent(txtTotalRecordCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNoData)
                .addGap(30, 30, 30))
        );

        newUpdateDeletePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New/Update/Delete Record"));

        jLabel1.setText("Address ID:");

        txtAddressID.setEnabled(false);

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblEmail.setText("Email:");

        lblPhoneNum.setText("Phone Number:");

        btnNewEntry.setText("Insert New Entry");
        btnNewEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEntryActionPerformed(evt);
            }
        });

        btnUpdateEntry.setText("Update Entry");
        btnUpdateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEntryActionPerformed(evt);
            }
        });

        btnDeleteEntry.setText("Delete Entry");
        btnDeleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newUpdateDeletePanelLayout = new javax.swing.GroupLayout(newUpdateDeletePanel);
        newUpdateDeletePanel.setLayout(newUpdateDeletePanelLayout);
        newUpdateDeletePanelLayout.setHorizontalGroup(
            newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUpdateDeletePanelLayout.createSequentialGroup()
                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUpdateDeletePanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(newUpdateDeletePanelLayout.createSequentialGroup()
                                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhoneNum)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtAddressID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newUpdateDeletePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnNewEntry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateEntry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteEntry)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newUpdateDeletePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteEntry, btnNewEntry, btnUpdateEntry});

        newUpdateDeletePanelLayout.setVerticalGroup(
            newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUpdateDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtAddressID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPhoneNum)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(newUpdateDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewEntry)
                    .addComponent(btnUpdateEntry)
                    .addComponent(btnDeleteEntry))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        findPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Find"));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findPanelLayout = new javax.swing.GroupLayout(findPanel);
        findPanel.setLayout(findPanelLayout);
        findPanelLayout.setHorizontalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFind, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        findPanelLayout.setVerticalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        errorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Errors"));

        debugTextArea.setColumns(20);
        debugTextArea.setRows(5);
        jScrollPane1.setViewportView(debugTextArea);

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newUpdateDeletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browsePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newUpdateDeletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(browsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
      currentEntryIndex--;
      
      if ( currentEntryIndex < 0 )
         currentEntryIndex = numberOfEntries - 1;

      txtCurrentRecord.setText( "" + ( currentEntryIndex + 1 ) );
      updateCurrentSelectedRecord();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void txtCurrentRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentRecordActionPerformed
        updateCurrentSelectedRecord();
    }//GEN-LAST:event_txtCurrentRecordActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
      currentEntryIndex++;

      if ( currentEntryIndex >= numberOfEntries )
         currentEntryIndex = 0;

      txtCurrentRecord.setText( "" + ( currentEntryIndex + 1 ) );
      updateCurrentSelectedRecord();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
      if (txtFind.getText().equals("")){
          loadDatabase();
          return;
      }
      results = personQueries.getPeopleByLastName( txtFind.getText() );
      numberOfEntries = results.size();

      if ( numberOfEntries != 0 )
      {
          currentEntryIndex = 0;
          currentEntry = results.get(currentEntryIndex);
          txtAddressID.setText("" + currentEntry.getAddressID());
          txtFirstName.setText(currentEntry.getFirstName());
          txtLastName.setText(currentEntry.getLastName());
          txtEmail.setText(currentEntry.getEmail());
          txtPhoneNum.setText(currentEntry.getPhoneNumber());
          txtTotalRecordCount.setText("" + numberOfEntries);
          txtCurrentRecord.setText("" + (currentEntryIndex + 1));
          myJTable.setModel(personQueries);
          enableControls();
      }
      else{
          loadDatabase();
      }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnNewEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEntryActionPerformed
      int result = personQueries.addPerson( txtFirstName.getText(),
         txtLastName.getText(), txtEmail.getText(),
         txtPhoneNum.getText() );

      if ( result == 1 ){
         JOptionPane.showMessageDialog( this, "Person added!",
            "Person added", JOptionPane.PLAIN_MESSAGE );
      }else{
         JOptionPane.showMessageDialog( this, "Person not added!",
            "Error", JOptionPane.PLAIN_MESSAGE );
      }

      loadDatabase();
    }//GEN-LAST:event_btnNewEntryActionPerformed

    private void myJTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_myJTablePropertyChange

    }//GEN-LAST:event_myJTablePropertyChange

    private void btnDeleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEntryActionPerformed
    if (txtAddressID.getText().equals("")){
        return;
    }
    int result = personQueries.deletePerson( txtAddressID.getText());

      if ( result == 1 ){
         JOptionPane.showMessageDialog( this, "Person deleted!",
            "Person added", JOptionPane.PLAIN_MESSAGE );
      }else{
         JOptionPane.showMessageDialog( this, "Person not deleted!",
            "Error", JOptionPane.PLAIN_MESSAGE );
      }

      loadDatabase();
    }//GEN-LAST:event_btnDeleteEntryActionPerformed

    private void btnUpdateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEntryActionPerformed
    if (txtAddressID.getText().equals("")){
        return;
    }
        int result = personQueries.updatePerson( txtAddressID.getText(),
              txtFirstName.getText(),txtLastName.getText(),
              txtEmail.getText(),txtPhoneNum.getText() );

      if ( result == 1 ){
         JOptionPane.showMessageDialog( this, "Person updated!",
            "Person added", JOptionPane.PLAIN_MESSAGE );
      }else{
         JOptionPane.showMessageDialog( this, "Person not updated!",
            "Error", JOptionPane.PLAIN_MESSAGE );
      }

      loadDatabase();
    }//GEN-LAST:event_btnUpdateEntryActionPerformed


    private void updateCurrentSelectedRecord(){
      currentEntryIndex =
         ( Integer.parseInt( txtCurrentRecord.getText() ) - 1 );

      if ( numberOfEntries != 0 && currentEntryIndex < numberOfEntries )
      {
         currentEntry = results.get( currentEntryIndex );
         txtAddressID.setText("" + currentEntry.getAddressID() );
         txtFirstName.setText( currentEntry.getFirstName() );
         txtLastName.setText( currentEntry.getLastName() );
         txtEmail.setText( currentEntry.getEmail() );
         txtPhoneNum.setText( currentEntry.getPhoneNumber() );
         txtTotalRecordCount.setText( "" + numberOfEntries );
         txtCurrentRecord.setText( "" + ( currentEntryIndex + 1 ) );
         myJTable.changeSelection(currentEntryIndex, 0, false, false);

      } // end if
    }

    private void myJTableValueChanged(ListSelectionEvent evt) {
        if (evt.getValueIsAdjusting()){
            return; // if you don't want to handle intermediate selections
        }
        ListSelectionModel rowSM = (ListSelectionModel)evt.getSource();
        int selectedIndex = rowSM.getMinSelectionIndex();
        currentEntryIndex = selectedIndex;
        if (currentEntryIndex > -1){
            txtCurrentRecord.setText( "" + ( currentEntryIndex + 1 ) );
            updateCurrentSelectedRecord();
        }

    }
    
    private void loadDatabase(){
      try
      {
         results = personQueries.getAllPeople();
         numberOfEntries = results.size();
         txtAddressID.setText("");
         txtFirstName.setText("");
         txtLastName.setText("");
         txtEmail.setText("");
         txtPhoneNum.setText("");
         txtTotalRecordCount.setText( "" + numberOfEntries );
         txtCurrentRecord.setText("");
         myJTable.setModel(personQueries);

         if ( numberOfEntries > 0 ){
             enableControls();
         }else{
             disableControls();
         }

      } // end try
      catch ( Exception e )
      {
         e.printStackTrace();
      } // end catch        
    }
    
    private void enableControls(){
         btnNext.setEnabled( true );
         btnPrevious.setEnabled( true );
         txtCurrentRecord.setEnabled(true);
         lblNoData.setVisible(false);
         btnDeleteEntry.setEnabled(true);
         btnUpdateEntry.setEnabled(true);
    }
    
    private void disableControls(){
         btnNext.setEnabled( false );
         btnPrevious.setEnabled( false );
         txtCurrentRecord.setEnabled(false);
         lblNoData.setVisible(true);
         btnDeleteEntry.setEnabled(false);
         btnUpdateEntry.setEnabled(false);
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressBookDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel browsePanel;
    private javax.swing.JButton btnDeleteEntry;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNewEntry;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdateEntry;
    private javax.swing.JTextArea debugTextArea;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JPanel findPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNoData;
    private javax.swing.JLabel lblOf;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JTable myJTable;
    private javax.swing.JPanel newUpdateDeletePanel;
    private javax.swing.JTextField txtAddressID;
    private javax.swing.JTextField txtCurrentRecord;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtTotalRecordCount;
    // End of variables declaration//GEN-END:variables

}
